/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/cheflaptop.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Cube" position={[0, 8.91, 0]}>
          <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material_0.004']} />
          <mesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials['49']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cheflaptop.gltf')
