/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Brandon Westlake (https://sketchfab.com/dr.badass2142)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/retro-computer-setup-free-82eaf2047e0447a1bfea22482f1d1404
title: Retro Computer Setup (FREE)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/oldpc.gltf");
  return (
    <group scale={0.05} ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={
                nodes.retro_computer_setup_retro_computer_setup_Mat_0.geometry
              }
              material={materials.retro_computer_setup_Mat}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/oldpc.gltf");
