/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/waterfallDraco.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.31, 0.12, -0.02]} rotation={[0.22, 0.96, 0.06]} scale={0}>
        <mesh geometry={nodes.node_id54.geometry} material={materials['69']} position={[9.13, -131.81, 306]} scale={31.77} />
        <mesh geometry={nodes.node_id56.geometry} material={materials['70']} position={[9.13, -131.81, 306]} scale={31.77} />
        <mesh geometry={nodes.node_id58.geometry} material={materials['71']} position={[9.13, -131.81, 306]} scale={31.77} />
      </group>
    </group>
  )
}

useGLTF.preload('/waterfallDraco.gltf')
